apps/carts/urls.py
from django.urls import path
from apps.carts import views

app_name = 'carts'

urlpatterns = [
    path('cart-add/', views.CartAddView.as_view(), name='cart_add'),
    path('cart-change/', views.CartChangeView.as_view(), name='cart_change'),
    path('cart-remove/', views.CartRemoveView.as_view(), name='cart_remove'),
]

apps/products/urls.py
from django.urls import path

from . import views


app_name = 'product'

urlpatterns = [
    path('search/', views.CatalogView.as_view(), name='search'),
    path('<slug:category_slug>/', views.CatalogView.as_view(), name='catalog-detail'),
    path('product/<slug:product_slug>/', views.ProductView.as_view(), name='product-detail'),
]
 

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from debug_toolbar.toolbar import debug_toolbar_urls

from mysite.settings import DEBUG

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("apps.main.urls", namespace='main')),
    path('catalog/', include("apps.products.urls", namespace='catalog')),
    path('user/', include("apps.users.urls", namespace='user')),
    path('cart/', include("apps.carts.urls", namespace='cart')),
    path('orders/', include("apps.orders.urls", namespace='orders')),
] 

if DEBUG:
    urlpatterns += debug_toolbar_urls()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    

apps/products/models.py
from django.db import models
from django.urls import reverse


class Categories(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.CharField(max_length=200, unique=True, null=True, blank=True, verbose_name='URL')
    
    class Meta:
        db_table = 'category'
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ("id",)
    
    
    def __str__(self) -> str:
        return self.name
    

class Products(models.Model):
    name = models.CharField(max_length=150, unique=True, verbose_name='Название')
    slug = models.CharField(max_length=200, unique=True, null=True, blank=True,verbose_name='URL')
    description = models.TextField(blank=True, null=True, verbose_name='Описание')
    image = models.ImageField(upload_to='products_image', null=True, blank=True, verbose_name='Изображение')
    price = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Цена')
    discount = models.DecimalField(default=0.00, max_digits=7, decimal_places=2, verbose_name='Скидка в %')
    quantity = models.PositiveIntegerField(default=0, verbose_name='Количество')
    category = models.ForeignKey(to=Categories, on_delete=models.CASCADE, verbose_name='Категория')
    
    class Meta:
        db_table = 'product'
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['id']


    def __str__(self) -> str:
        return self.name
    
    def display_id(self):
        return f'{self.id:05}'
    
    def sell_price(self):
        if self.discount:
            return round(self.price - self.price * self.discount / 100, 2)
        
        return self.price
    
    def get_absolute_url(self):
        return reverse("catalog:product-detail", kwargs={"product_slug": self.slug})
    

apps/products/views.py
from django.views.generic import ListView, DetailView
from django.http import Http404

from apps.products.models import Products
from apps.products.utils import query_search


class CatalogView(ListView):
    model = Products
    # queryset = Products.objects.all()
    template_name = 'products/catalog.html'
    context_object_name = 'products'
    paginate_by = 6
    allow_empty = True
    
    def get_queryset(self):
        category_slug = self.kwargs.get('category_slug')
        on_sale = self.request.GET.get('on_sale')
        order_by = self.request.GET.get('order_by')
        query = self.request.GET.get('q')
        
        if category_slug == 'all':
            products = super().get_queryset()
        elif query:
            products = query_search(query)
        else:
            products = super().get_queryset().filter(category__slug=category_slug)
            if not products.exists():
                raise Http404()

        if on_sale:
            products = products.filter(discount__gt=0)
        if order_by and order_by != 'default':
            products = products.order_by(order_by)
            
        return products
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Home - Каталог'
        context['category_slug'] = self.kwargs.get('category_slug')
        return context


class ProductView(DetailView):
    # model = Products
    # slug_field = 'slug'
    template_name = 'products/product.html'
    slug_url_kwarg = 'product_slug'
    context_object_name = 'product'
    
    def get_object(self, queryset=None):
        product = Products.objects.get(slug=self.kwargs.get(self.slug_url_kwarg))
        return product

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.object.name
        return context


# def catalog(request, category_slug=None):
#     on_sale = request.GET.get('on_sale', None)
#     order_by = request.GET.get('order_by', None)
#     query = request.GET.get('q', None)
    
#     if category_slug == 'all':
#         products = Products.objects.all()
#     elif query:
#         products = query_search(query)
#     else:
#         products = Products.objects.filter(category__slug=category_slug)
        
#         if not products.exists():
#             raise Http404()

#     if on_sale:
#         products = products.filter(discount__gt=0)
#     if order_by and order_by != 'default':
#         products = products.order_by(order_by)
    
#     paginator = Paginator(products, 6)
#     page_number = request.GET.get('page')
#     page_obj = paginator.get_page(page_number)  
    
#     context = {
#         'title': 'Home - Каталог',
#         'products': page_obj,
#         'category_slug': category_slug,
#     }
    
#     return render(request, template_name='products/catalog.html', context=context)


# def product(request, product_slug):
#     product = get_object_or_404(Products, slug=product_slug)
    
#     context = {
#         'product': product,
#     }
    
#     return render(request, template_name='products/product.html', context=context)
 

apps/products/templates/products/catalog.html
    {% extends "base.html" %}
{% load static %}
{% load products_tags %}

{% block cart_button %}
    {% include "includes/cart_button.html" %}
{% endblock cart_button %}


{% block content %}

    <div class="row">
        <!-- Форма фильтров -->
        <div class="dropdown mb-2">
            <button class="btn btn-secondary dropdown-toggle btn-dark" type="button" data-bs-toggle="dropdown"
                aria-expanded="false">
                Фильтры
            </button>
    
            <form action="{% if request.GET.q %}{% url "catalog:search" %} {% else %} {% url "catalog:catalog-detail" category_slug %} {% endif %}"  method="get" class="dropdown-menu bg-dark" data-bs-theme="dark">
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="checkbox" name="on_sale" id="flexCheckDefault" value="on"
                    {% if request.GET.on_sale == 'on' %} checked {% endif %}>
                    {% if  request.GET.q %}
                        <input type="hidden" name="q" value="{{ request.GET.q }}">
                    {% endif %}
                    <label class="form-check-label" for="flexCheckDefault">
                        Товары по акции
                    </label>
                </div>
                <p class="text-white mx-3 mt-3">Сортировать:</p>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault1" value="default" checked
                    {% if not request.GET.order_by or request.GET.order_by == 'default' %} checked {% endif %}>
                    <label class="form-check-label" for="flexRadioDefault1">
                        По умолчанию
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault2" value="price"
                    {% if request.GET.order_by == 'price' %} checked {% endif %}>
                    <label class="form-check-label" for="flexRadioDefault2">
                        От дешевых к дорогим
                    </label>
                </div>
                <div class="form-check text-white mx-3">
                    <input class="form-check-input" type="radio" name="order_by" id="flexRadioDefault3" value="-price"
                    {% if request.GET.order_by == '-price' %} checked {% endif %}>
                    <label class="form-check-label" for="flexRadioDefault3">
                        От дорогих к дешевым
                    </label>
                </div>
                <button type="submit" class="btn btn-primary mx-3 mt-3">Применить</button>
            </form>
        </div>
        <!-- Карта товара -->

        {% if request.GET.q %}
        <h3 class="mt-4">Результаты поиска по запросу "{{ request.GET.q }}"</h3>
        {% if not products %}
            <h2 class="mt-4">По запросу ничего не найдено</h2>
        {% endif %}
        {% endif %}

            {% for product in products %}
        <div class="col-lg-4 col-md-6 p-4">
            <div class="card border-primary rounded custom-shadow">
                {% if product.image %}
                    <img src="{{ product.image.url }}" class="card-img-top" alt="...">
                {% else %}
                    <img src="{% static "images/Not found image.png" %}" class="card-img-top" alt="...">
                {% endif %}
                <div class="card-body">
                    <a href="{% url 'catalog:product-detail' product.slug %}">
                        {% autoescape off %}
                            <p class="card-title"> 
                                {% if  product.headline %} 
                                    {{ product.headline }} 
                                {% else %} 
                                    {{ product.name }} 
                                {% endif %} 
                            </p>
                        {% endautoescape %}
                    </a>
                    <p class="card-text ">
                        {% autoescape off %}
                            <p class="card-title"> 
                                {% if  product.bodyline %} 
                                    {{ product.bodyline|truncatechars:70 }} 
                                {% else %} 
                                    {{ product.description|truncatechars:30 }}
                                {% endif %} 
                            </p>
                        {% endautoescape %}
                    </p>
                    <p class="product_id">id: {{ product.display_id }}</p>
                    <div class="d-flex justify-content-between">
                        {% if product.discount %}
                            <p><s>{{ product.price }}</s> $</p>
                            <p><strong>{{product.sell_price}} $</strong></p>
                            <span class="badge bg-warning text-dark">Скидка {{ product.discount }} %</span>
                        {% else %}
                            <p><strong>{{ product.price }} $ </strong></p>
                        {% endif %}
                        <a href="{% url "cart:cart_add" %}" class="btn add-to-cart"
                        data-product-id="{{ product.id }}"> {% csrf_token %}
                            <img class="mx-1" src="{% static "icons/cart-plus.svg" %}" alt="Catalog Icon"
                                width="32" height="32">
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    <!-- Пагинация -->
    {% if products %}
        <nav aria-label="Page navigation example">
            <ul class="pagination justify-content-center my-4">
                <div class="custom-shadow d-flex">

                    <li class="page-item {% if not page_obj.has_previous %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_previous %}?{% tag_products page=page_obj.previous_page_number %}{% endif %}">
                            Предыдущий
                        </a>
                    </li>
                    
                    {% for page in page_obj.paginator.page_range %}
                        {% if page >= page_obj.number|add:-2 and page <= page_obj.number|add:2 %}
                            <li class="page-item {% if page == page_obj.number %} active {% endif %}">
                                <a class="page-link" href="?{% tag_products page=page %}">{{ page }}</a>
                            </li>
                        {% endif %}
                    {% endfor %}
                    
                    <li class="page-item {% if not page_obj.has_next %} disabled {% endif %}">
                        <a class="page-link" href="{% if page_obj.has_next %}?{% tag_products page=page_obj.next_page_number %}{% endif %}">
                            Следующий
                        </a>
                    </li>                            
                    
                </div>
            </ul>
        </nav>
    {% endif %}

{% endblock content %}    

apps/products/templates/products/product.html
{% extends "base.html" %}
{% load static %}

{% block cart_button %}
    {% include "includes/cart_button.html" %}
{% endblock cart_button %}

{% block content %}

    <div class="container mt-5">
        <div class="card mb-4 custom-shadow">
            <div class="row">
                <!-- Миниатюры -->
                <div class="col-md-4">
                    {% if product.image %}
                        <img src="{{ product.image.url }}"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                    {% else %}
                        <img src="{% static "images/Not found image.png" %}"
                        class="img-thumbnail" data-bs-toggle="modal" data-bs-target="#imageModal1">
                    {% endif %}
                </div>
                <div class="col-md-4 ">
                    <p class="product_id mt-3">id: {{product.display_id}}</p>
                </div>
                <!-- Увеличить изображение в модальном окне -->
                <div class="modal fade" id="imageModal1" tabindex="-1"
                    aria-labelledby="imageModal1Label" aria-hidden="true">
                    <div class="modal-dialog modal-lg">
                        <div class="modal-content">
                            <div class="modal-header">
                                <h5 class="modal-title" id="imageModal1Label">Изображение 1</h5>
                                <button type="button" class="btn-close" data-bs-dismiss="modal"
                                    aria-label="Закрыть"></button>
                            </div>
                            <div class="modal-body">
                                <img src="{{ product.image.url }}"
                                    class="img-fluid" alt="Изображение 1">
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Описание товара -->
            <div class="card-body">
                <p class="card-text">Цена: <strong>{{ product.sell_price }} $</strong></p>
                <h5 class="card-title">{{ product.name }}</h5>
                <p class="card-text">{{ product.description }}</p>
                <a href="{% url "cart:cart_add" %}" class="btn btn-dark add-to-cart"
            data-product-id="{{ product.id }}"> {% csrf_token %} Добавить в корзину</a>
            </div>
        </div>
    </div>

{% endblock content %}